import graphqlDocs from "./graphql.mjs"

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
    docsSidebar: [{ type: "autogenerated", dirName: "docs" }],
    graphqlSidebar: graphqlDocs.map((doc) => {
        const name = doc.id[0].toUpperCase() + doc.id.slice(1);
        return {
            type: "category",
            label: name,
            link: {
                type: "doc",
                id: `graphql/${doc.id}/schema`
            },
            items: [{
                type: "autogenerated",
                dirName: `graphql/${doc.id}`
            }]
        };
    })
};
